# $Id: Makefile,v 1.1.2.1 Broadcom SDK $
# 
# This license is set out in https://github.com/Broadcom/Broadcom-Compute-Connectivity-Software-robo2-xsdk/master/Legal/LICENSE file.
#
# $Copyright: (c) 2020 Broadcom Inc.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
# Makefile for BCM driver Library
#

LOCALDIR = src/bcm/ea/common

include ${SDK}/make/Make.config
include ${SDK}/make/Make.subdirs
	
lib = libbcm_eacommon

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend

