/*
 * DO NOT EDIT THIS FILE!
 * This file is auto-generated.
 * Edits to this file will be lost when it is regenerated.
 *
 * $Id: $
 * 
 * This license is set out in https://github.com/Broadcom/Broadcom-Compute-Connectivity-Software-robo2-xsdk/master/Legal/LICENSE file.
 *
 * $Copyright: (c) 2020 Broadcom Inc.
 * Broadcom Proprietary and Confidential. All rights reserved.$
 *
 * File:	xapi_ref.h
 * Purpose:	BCMX API routines reference
 * Generator:	mkdispatch 1.51
 * Generated:	Mon Oct 15 09:04:23 2012
 */

#ifndef	_BCMX_API_REF_H
#define	_BCMX_API_REF_H

typedef void (*bcmx_api_ref_t)(void);

extern bcmx_api_ref_t bcmx_api_tbl[];

#endif	/* !_BCMX_API_REF_H */
