# -*- Makefile -*-
# $Id: Makefile,v 1.2 Broadcom SDK $
# 
# This license is set out in https://github.com/Broadcom/Broadcom-Compute-Connectivity-Software-robo2-xsdk/master/Legal/LICENSE file.
#
# $Copyright: (c) 2020 Broadcom Inc.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
LOCALDIR = systems/linux/kernel/modules/shared

include ${SDK}/make/Make.config

lib = libkern

include ${SDK}/make/Make.kernlib

include ${SDK}/make/Make.depend
