#
# $Id:$
# 
# This license is set out in https://github.com/Broadcom/Broadcom-Compute-Connectivity-Software-robo2-xsdk/master/Legal/LICENSE file.
#
# $Copyright: (c) 2020 Broadcom Inc.
# Broadcom Proprietary and Confidential. All rights reserved.$
# 
# Makefile for SOC swstate subdirectory
#
LOCALDIR = src/soc/hwstate

include ${SDK}/make/Make.config

lib = libsoc_hwstate

include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend