# -*- Makefile -*-
# $Id: Makefile,v 1.3 Broadcom SDK $
# 
# This license is set out in https://github.com/Broadcom/Broadcom-Compute-Connectivity-Software-robo2-xsdk/master/Legal/LICENSE file.
#
# $Copyright: (c) 2020 Broadcom Inc.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
# Makefile for StrataXGS SDK and diagnostics
#

include $(SDK)/make/Make.config

ifeq ($(HOSTTYPE),i386-linux)
subdirs= kernel user
endif

include $(SDK)/make/Make.subdirs

include $(SDK)/make/Make.depend

