# $Id: Makefile,v 1.5 Broadcom SDK $
# 
# This license is set out in https://github.com/Broadcom/Broadcom-Compute-Connectivity-Software-robo2-xsdk/master/Legal/LICENSE file.
#
# $Copyright: (c) 2020 Broadcom Inc.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
# Makefile for SOC SAL support
#

LOCALDIR = src/sal/appl

include ${SDK}/make/Make.config

subdirs=${targetbase} editline

include ${SDK}/make/Make.subdirs


lib = libsal_appl

include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend



