# -*- Makefile -*-
# $Id: $
# 
# This license is set out in https://github.com/Broadcom/Broadcom-Compute-Connectivity-Software-robo2-xsdk/master/Legal/LICENSE file.
#
# $Copyright: (c) 2020 Broadcom Inc.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
# Makefile for BCM compat driver Library
#

LOCALDIR = src/bcm/compat

include ${SDK}/make/Make.config

lib = libbcm_compat
include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend
