# -*- Makefile -*-
# $Id: Makefile,v 1.2 Broadcom SDK $
# 
# This license is set out in https://github.com/Broadcom/Broadcom-Compute-Connectivity-Software-robo2-xsdk/master/Legal/LICENSE file.
#
# $Copyright: (c) 2020 Broadcom Inc.
# Broadcom Proprietary and Confidential. All rights reserved.$
#

include ${SDK}/make/Make.config

subdirs= shared bcm-diag-proxy

include ${SDK}/make/Make.subdirs

include ${SDK}/make/Make.depend
