# $Id: Makefile,v 1.3 Broadcom SDK $
# 
# This license is set out in https://github.com/Broadcom/Broadcom-Compute-Connectivity-Software-robo2-xsdk/master/Legal/LICENSE file.
#
# $Copyright: (c) 2020 Broadcom Inc.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
# Makefile for SOC SAL support (Unix)
#
LOCALDIR = src/sal/appl/linux

include ${SDK}/make/Make.config

lib = libsal_appl_plat
include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend
