# -*- Makefile -*-
# $Id: Makefile,v 1.10 Broadcom SDK $
# 
# This license is set out in https://github.com/Broadcom/Broadcom-Compute-Connectivity-Software-robo2-xsdk/master/Legal/LICENSE file.
#
# $Copyright: (c) 2020 Broadcom Inc.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
# Makefile for SOC SAL support
#
LOCALDIR = systems/linux/kernel/modules

include ${SDK}/make/Make.config

subdirs=shared uk-proxy bcm-diag-full bcm-core bcm-net bcm-diag

include ${SDK}/make/Make.subdirs

include ${SDK}/make/Make.depend
