# -*- Makefile -*-
# $Id: Makefile,v 1.1 Broadcom SDK $
# 
# This license is set out in https://github.com/Broadcom/Broadcom-Compute-Connectivity-Software-robo2-xsdk/master/Legal/LICENSE file.
#
# $Copyright: (c) 2020 Broadcom Inc.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
# Makefile for SOC driver Library
#
LOCALDIR = src/soc/robo/gex/lotus

include ${SDK}/make/Make.config

lib = libsocrobo_lotus
include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend
