# -*- Makefile -*-
# $Id: Makefile,v 0.1  Exp $
# 
# This license is set out in https://github.com/Broadcom/Broadcom-Compute-Connectivity-Software-robo2-xsdk/master/Legal/LICENSE file.
#
# $Copyright: (c) 2020 Broadcom Inc.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
# Makefile for avenger FSAL Library
#

LOCALDIR = src/appl/dot1as

include ${SDK}/make/Make.config

CFLAGS += -D_SHR_PBMP_WIDTH=0

lib = libdot1as
include ${SDK}/make/Make.lib

include ${SDK}/make/Make.depend
