# $Id: Makefile,v 1.5 Broadcom SDK $
# 
# This license is set out in https://github.com/Broadcom/Broadcom-Compute-Connectivity-Software-robo2-xsdk/master/Legal/LICENSE file.
#
# $Copyright: (c) 2020 Broadcom Inc.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
# Makefile for SOC SAL support (Linux Kernel)
#
LOCALDIR = src/sal/core/linux

include ${SDK}/make/Make.config

lib = libsal_core_plat
include ${SDK}/make/Make.kernlib

include ${SDK}/make/Make.depend
