# -*- Makefile -*-
# $Id: Makefile,v 1.1 Broadcom SDK $
# 
# This license is set out in https://github.com/Broadcom/Broadcom-Compute-Connectivity-Software-robo2-xsdk/master/Legal/LICENSE file.
#
# $Copyright: (c) 2020 Broadcom Inc.
# Broadcom Proprietary and Confidential. All rights reserved.$
#
LOCALDIR = src/appl/diag/cint

include ${SDK}/make/Make.config

CFGFLAGS += -I$(SDK)/src/appl/cint

lib = libdiagcint
include ${SDK}/make/Make.lib
include ${SDK}/make/Make.depend
